### ISSUE TITLE
Nothing Appearing on Bugsnag Dashboard

### ISSUE THREAD

**Issue by mliyanagamage** [awseward/Bugsnag.NET#23]
Hi,

I have been using your library for my UWP application. I following exactly what was in your README. The library appears to be working, I receive a 200 OK for every test notify that I do. But nothing appears on the bugsnag dashboard. I have checked my API keys and they look correct. The only thing I do notice is that I am using the `Bugsnag.PCL` namespace. Any help with this problem would be much appreciated.

**Comment by mglodack** [comment]
@mliyanagamage Would you mind pasting a snippet of what your code looks like?

**Comment by mliyanagamage** [comment]
@mglodack Thanks for responding, I have put up the code on a gist [here](https://gist.github.com/mliyanagamage/ad987a25cecedf86e285597515b2fa70)

**Comment by mglodack** [comment]
@mliyanagamage  Everything looks okay at first glance. 

I will take a more in depth look later tonight.

**Comment by mliyanagamage** [comment]
I cloned the repository and added it as a reference instead of the Nuget package. Everything looks good, although the bugsnag api docs do say the 200 OK means

>The payload was accepted and will be processed asynchronously. This doesn't imply that your payload was valid, just that it was enqueued to be processed.

Is there a chance that the payload is invalid is some way? A quick comparison between the example payload and the payload sent doesn't seem any different to me, but I could be wrong.

**Comment by alisio92** [comment]
I have the same issue. I also get a status code 200, but it doesn't appear anything on the dashboard.
I have a similar class, but i do set the Notifier url to https://notify.bugsnag.com.

**Comment by mliyanagamage** [comment]
So, I had time on my hands so I cloned the Bugsnag.NET official package and retargeted it to UWP. Stripped and hacked anything optional/incompatible away and got it to work. It had the same problem where you would get a status code 200 and not have anything on the dashboard.

I had a chat with the Bugsnag people and found a simple issue. In the payload going out the `exception` key was always `null`, this automatically disqualified it from processing and is silently rejected by the bugsnag API. The reason was their package did not add an exception if the stacktrace is empty. So in order for the API to accept a payload there must be stacktrace in order for the exception to be valid. 

The reason for the lack of stacktrace is that .NET only populates that field if the exception is thrown. So I simply threw an exception, caught it and notified bugsnag and immediately had it appear of the dashboard. The recommended work around is for non-exception notifies to have a separate interface which would spoof a stack trace in. I haven't got around to look into that yet

Hope this helps

**Comment by alisio92** [comment]
thanks, i'm trying it now.

**Comment by IgorBurakov** [comment]
As far as I know this issue was resolved by commit https://github.com/awseward/Bugsnag.NET/commit/a6d7fa5fe4eb2a61739259c0b586204f94ac9d4b
Maybe it is just not picked up for UWP version

**Comment by alisio92** [comment]
thanks it works.

**Comment by alisio92** [comment]
the only annoying part is now that i get a custom exception now instead of the actual exception.

**Comment by awseward** [comment]
@mliyanagamage Thanks so much for investigating this!

> The recommended work around is for non-exception notifies to have a separate interface which would spoof a stack trace in. I haven't got around to look into that yet

Should I await a PR with this workaround, or can I get started on resolving it later today?

**Comment by mliyanagamage** [comment]
@awseward Working on one now, will keep you updated

**Comment by mliyanagamage** [comment]
@awseward So there are two ways to go about this. One is to hack in a fake stack trace [here](https://github.com/awseward/Bugsnag.NET/blob/master/Bugsnag.PCL/Extensions/Extensions.cs#L29). Probably add a line of text that looks like it was from a stacktrace but has dummy information in order to allow the parsers found in `StackTraceLine` to parse through them correctly. 

The alternative method is to create a separate method for notification exceptions (not thrown exceptions) which would use [Caller Information](https://msdn.microsoft.com/en-us/library/hh534540(v=vs.110).aspx) to generate a slightly more useful stacktrace. 

Opinions?

**Comment by awseward** [comment]
I like the idea of the caller information approach, but I'd like to make sure I'm totally clear on what that will actually give us.

To me it seems like we'll only really able to get information about where the consuming application has called `client.Notify(...)`. If that is indeed the case, I'm not sure how valuable that information really is to a developer, as the location of error reporting code would typically be centralized and not very dynamic, right?

However, if that's not the case and I'm simply mistaken, I'm curious to hear in more detail what you have in mind for that approach.

**Comment by awseward** [comment]
Also, just for clarification about compatibility, the only constraints using Caller Information would add is a requirement to be using at least VS2012.

I don't see this as a problem, just want to make sure.

**Comment by mliyanagamage** [comment]
I just realized you are totally right, it's really up to the developer to implement a helper which can uses caller information, what we should do is provide GetEvent overload method which can take in values derived from caller information and spoof a `StackTraceLine` so that notifications have more information than some useless dummy data. Does that sound right?

**Comment by awseward** [comment]
That sounds good to me.

We should also still update [this](https://github.com/awseward/Bugsnag.NET/blob/master/Bugsnag.PCL/Extensions/Extensions.cs#L27-L30) to match [this](https://github.com/awseward/Bugsnag.NET/blob/master/Bugsnag.NET/Extensions/Extensions.cs#L28-L31) for consistency. The PCL project was created under a bit of time constraint, and the work of consolidating duplicated code simply hasn't been done yet.

It looks like the `ToLines` extension was updated in the Bugsnag.NET project, but not the Bugsnag.PCL one

**Comment by mliyanagamage** [comment]
Cool I will get on it this weekend

**Comment by awseward** [comment]
Fantastic. In the meantime while you're looking into that, I'm going to go ahead with https://github.com/awseward/Bugsnag.NET/pull/25 as a short-term solution to this issue.

**Comment by awseward** [comment]
@mliyanagamage: Didn't notice you already had done that in https://github.com/mliyanagamage/Bugsnag.NET/commit/67378656e82e6659f33ee43bc00e4114f5add2e0.

You may see a conflict as a result on next pull, sorry about that!

**Comment by mliyanagamage** [comment]
No biggy, made some early progress, will share after I have tested it for your opinion.

**Comment by awseward** [comment]
Sounds good, looking forward to it!
