### ISSUE TITLE
Meta data and device is not shown in dashboard(UWP)

### ISSUE THREAD

**Issue by alisio92** [awseward/Bugsnag.NET#24]
I can't see the device or my metadata in the dashboard.
All other values like user, app i do get.

```
 var evt = client.GetEvent(exception, GetCurrentUser(), GetDevice(), GetMetadata());
 private static object GetMetadata()
    {
        return "This is MetaData";
    }

private BsNet.Request.IDevice GetDevice()
    {
        return new BSDevice();
    }

public class BSDevice : BsNet.Request.IDevice
{
    public string Hostname
    {
        get { return "host"; }
    }

    public string OsVersion
    {
        get {return "OS"; }
    }
}
```

**Comment by awseward** [comment]
I'm not sure at first glance why the device might not be working, but there is something I might ask you to try for the metadata part.

I believe it it may work if you give it an anonymous object as opposed to just a string.
Try something like this, and let me know if you have better luck with it:
```cs
private static object GetMetaData()
{
    return new {
        someKey = "someValue",
    };
}
```

**Comment by alisio92** [comment]
Yes it works. It makes a tab named Custom. Is it possible to name it?

**Comment by awseward** [comment]
I just glanced at their docs and it looks like it may be possible if you nest your keys/values one level deeper.

It may be worth trying something like this and seeing if that works:
```cs
return new {
    firstTab = new {
        someKey = "someValue",
    },
    secondTab = new {
        someKey = "someValue",
    },
};
```

**Comment by alisio92** [comment]
Yes that works as well. Thanks

**Comment by awseward** [comment]
Are you still not seeing the device showing up?

**Comment by alisio92** [comment]
Did you change something? if not then no. But now with the metadata i can create one myself.

**Comment by awseward** [comment]
No, nothing has changed. I was mostly wondering if maybe the metadata was somehow causing the device fields to fail.

It sounds like that's not the case, though.
